title: 白夜書簡
subtitle: 以夜為箋，寄心成簡。
description: 夜白，字輕。
keywords: 白夜, Acris, Java, Linux, Code, Blog
author: 白夜
language: zh-CN

url: https://acris.me
pretty_urls:
  trailing_index: false
  trailing_html: false

index_generator:
  per_page: 5

theme: shiro
